### ISSUE TITLE
Realtime Postgres updates unreliable / not working

### ISSUE THREAD

**Issue by colin-chadwick** [supabase-community/supabase-on-aws#90]
# Bug report

Realtime is unable to broadcast most Postgres changes. It sometimes works, but is really unreliable. All other realtime events, for e. g. presence states or cursor positions work as expected.

## To Reproduce

Simply deploy the stack on AWS, in my case I deployed it in eu-west-1 region. I chose micro Fargate task size.

## Expected behavior

Listening to Postgres changes should work just like in the hosted version.

## Screenshots

Maybe this has something to do with realtime not being able to correctly connect to the RDS database? These logs are shown in the realtime logs when trying to watch Postgres changes:

![Bildschirmfoto 2024-03-19 um 18 11 23](https://github.com/supabase-community/supabase-on-aws/assets/62803839/8dfc21a3-e58e-49bd-862f-beaa0deb5fc5)

**Comment by colin-chadwick** [comment]
It looks like the Supabase on AWS template isn't compatible with newer versions of Realtime. I was able to get this to work by setting the `ERL_AFLAGS` environment variable from `-proto_dist inet_tcp` to `-proto_dist inet6_tcp`. The `DNS_NODES` variable is important as well.  Here's the entire configuration: 
```yaml
environment: {
          PORT: '4000',
          DB_HOST: db.cluster.clusterEndpoint.hostname,
          DB_PORT: db.cluster.clusterEndpoint.port.toString(),
          DB_AFTER_CONNECT_QUERY: 'SET search_path TO realtime',
          DB_ENC_KEY: 'supabaserealtime',
          FLY_ALLOC_ID: 'fly123',
          FLY_APP_NAME: `realtime`,
          ERL_AFLAGS: '-proto_dist inet6_tcp',
          ENABLE_TAILSCALE: 'false',
          DNS_NODES: `realtime-dev.${namespaceName}`,
        },
secrets: {
          DB_USER: ecs.Secret.fromSecretsManager(
            supabaseAdminSecret,
            'username',
          ),
          DB_PASSWORD: ecs.Secret.fromSecretsManager(
            supabaseAdminSecret,
            'password',
          ),
          DB_NAME: ecs.Secret.fromSecretsManager(supabaseAdminSecret, 'dbname'),
          API_JWT_SECRET: ecs.Secret.fromSecretsManager(jwtSecret),
          SECRET_KEY_BASE: ecs.Secret.fromSecretsManager(cookieSigningSecret),
}
```
